# Generated by Django 5.1.4 on 2024-12-26 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_service', '0001_initial'),
        ('product_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_service.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_service.vendor')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='payment_ser_order_i_e6c69b_idx'), models.Index(fields=['vendor'], name='payment_ser_vendor__4fc59d_idx'), models.Index(fields=['status'], name='payment_ser_status_65ff15_idx')],
            },
        ),
    ]
