# Generated by Django 5.1.4 on 2024-12-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0002_remove_orderitem_order_remove_orderitem_product_and_more'),
        ('payment_service', '0002_alter_payment_order_alter_payment_status_and_more'),
        ('shipment_service', '0002_alter_shipment_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddIndex(
            model_name='orderservice',
            index=models.Index(fields=['estimated_delivery'], name='order_servi_estimat_002fa2_idx'),
        ),
    ]
